services:
  orthanc:
    image: jodogne/orthanc-plugins:latest  # ใช้อิมเมจที่อัปเดต
    container_name: pacs_server
    restart: always
    ports:
      - "4242:4242"  # DICOM port
      - "8042:8042"  # Web UI / REST API port
    environment:
      ORTHANC_NAME: "MyPACS"
      ORTHANC__DICOM_AET: "ORTHANC"
      ORTHANC__DICOM_PORT: 4242
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      ORTHANC__REGISTERED_USERS: '{"admin": "password"}'
    volumes:
      - orthanc_data:/var/lib/orthanc/db
      - ./config/test.json:/etc/orthanc/orthanc.json  # ใช้ config ใหม่

volumes:
  orthanc_data: